# Generated by Django 2.1.7 on 2019-03-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('author', models.CharField(max_length=100, unique=True, verbose_name='作者')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='标签')),
                ('body', models.TextField(verbose_name='内容')),
                ('posted', models.DateField(auto_now_add=True, db_index=True, verbose_name='提交日期')),
            ],
        ),
    ]
